### ISSUE TITLE
Maintainer is missing

### ISSUE THREAD

**Issue by diamondburned** [flathub/so.libdb.gtkcord4#5]
It appears that the account of the primary maintainer of this repository has been deleted off GitHub, so I don't think this repository is maintained anymore. It is 1 version behind the latest version, currently.

It might be reasonable to consider the Flatpak package as outdated/deprecated for now until we have someone else who wants to take up the work.

**Comment by tfuxu** [comment]
I can work on maintaining it

**Comment by diamondburned** [comment]
@tfuxu, you should be able to make an issue on https://github.com/flathub/flathub/issues about this, and I can drop a comment there afterwards.

**Comment by tfuxu** [comment]
Done, @diamondburned you can close issue in upstream, as I received write access to the package. 
New release should show up tomorrow, as I'm currently working on PR.
