### ISSUE TITLE
Rebrand to Dissent

### ISSUE THREAD

**Issue by diamondburned** [flathub/so.libdb.gtkcord4#9]
The app ID has been changed again :(

Please see https://github.com/diamondburned/dissent/issues/226.

**Comment by tfuxu** [comment]
No problem, I'll file an issue ~tomorrow~ to archive this repo.

https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life-rebase

**Comment by diamondburned** [comment]
Hi, is there any update on this?

**Comment by tfuxu** [comment]
I've already created a PR on Flathub: https://github.com/flathub/flathub/pull/5004. It works with nightly release, but I had problems with 0.19.0, so I'm currently just waiting for 0.20.0.

**Comment by diamondburned** [comment]
It's out now!
